# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'mainwid.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from PyQt5.QtWidgets import QWidget

from 界面 import showpanel, mapshow, rank


class query_window(showpanel.Ui_showwid, QWidget):
    def __init__(self):
        super(query_window, self).__init__()
        self.setupUi(self)

class map_window(mapshow.Ui_Form, QWidget):
    def __init__(self):
        super(map_window, self).__init__()
        self.setupUi(self)

class rank_window(rank.Ui_rankwid, QWidget):
    def __init__(self):
        super(rank_window, self).__init__()
        self.setupUi(self)

class Ui_mainwid(QWidget):
    app = QtWidgets.QApplication(sys.argv)
    query_window = query_window()
    map_window = map_window()
    rank_window = rank_window()
    def setupUi(self, mainwid):
        mainwid.setObjectName("mainwid")
        mainwid.resize(903, 806)
        mainwid.setMinimumSize(QtCore.QSize(100, 100))
        mainwid.setMaximumSize(QtCore.QSize(1000, 1001))
        font = QtGui.QFont()

        font.setPointSize(16)
        mainwid.setFont(font)

        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("nuan.jpg")))
        mainwid.setPalette(palette)

        self.namebtn = QtWidgets.QLabel(mainwid)
        self.namebtn.setGeometry(QtCore.QRect(290, 80, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.namebtn.setFont(font)

        self.namebtn.setObjectName("namebtn")
        self.pstbtn = QtWidgets.QPushButton(mainwid)
        self.pstbtn.setGeometry(QtCore.QRect(220, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pstbtn.setFont(font)
        self.pstbtn.setStyleSheet("border-image: url(:/R.jpg);\n"
"QPushButton\n"
"{\n"
"    border-radius: 6px; \n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:5px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.pstbtn.setObjectName("pstbtn")
        self.predictbtn = QtWidgets.QPushButton(mainwid)
        self.predictbtn.setGeometry(QtCore.QRect(470, 300, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.predictbtn.setFont(font)
        self.predictbtn.setStyleSheet("border-image: url(:/R.jpg);\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.predictbtn.setObjectName("predictbtn")
        self.updatebtn = QtWidgets.QPushButton(mainwid)
        self.updatebtn.setGeometry(QtCore.QRect(220, 450, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.updatebtn.setFont(font)
        self.updatebtn.setStyleSheet("border-image: url(:/R.jpg);")
        self.updatebtn.setObjectName("updatebtn")
        self.mapbtn = QtWidgets.QPushButton(mainwid)
        self.mapbtn.setGeometry(QtCore.QRect(470, 380, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mapbtn.setFont(font)
        self.mapbtn.setStyleSheet("border-image: url(:/R.jpg);\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.mapbtn.setObjectName("mapbtn")
        self.uploadbtn = QtWidgets.QPushButton(mainwid)
        self.uploadbtn.setGeometry(QtCore.QRect(470, 450, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.uploadbtn.setFont(font)
        self.uploadbtn.setStyleSheet("border-image: url(:/R.jpg);")
        self.uploadbtn.setObjectName("uploadbtn")
        self.rankbtn = QtWidgets.QPushButton(mainwid)
        self.rankbtn.setGeometry(QtCore.QRect(220, 380, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.rankbtn.setFont(font)
        self.rankbtn.setStyleSheet("border-image: url(:/R.jpg);\n"
"QPushButton\n"
"{\n"
"    border-radius: 6px; \n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.rankbtn.setObjectName("rankbtn")

        self.retranslateUi(mainwid)
        QtCore.QMetaObject.connectSlotsByName(mainwid)

        self.pstbtn.clicked.connect(self.query_window.show)
        self.mapbtn.clicked.connect(self.map_window.show)
        self.rankbtn.clicked.connect(self.rank_window.show)

    def retranslateUi(self, mainwid):
        _translate = QtCore.QCoreApplication.translate
        mainwid.setWindowTitle(_translate("mainwid", "welcome"))
        self.namebtn.setText(_translate("mainwid", "天气质量查询与预测系统"))
        self.pstbtn.setText(_translate("mainwid", "查询历史数据"))
        self.predictbtn.setText(_translate("mainwid", "预测未来情况"))
        self.updatebtn.setText(_translate("mainwid", "更新数据"))
        self.mapbtn.setText(_translate("mainwid", "地图展示"))
        self.uploadbtn.setText(_translate("mainwid", "上传数据预测"))
        self.rankbtn.setText(_translate("mainwid", "城市对比排名"))


