# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'mapshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QWidget

from 文件操作.eggy import generate_map


class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1550, 900)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("nuan.jpg")))
        Form.setPalette(palette)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.idexbox = QtWidgets.QComboBox(Form)
        self.idexbox.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.idexbox.setFont(font)
        self.idexbox.setObjectName("idexbox")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.idexbox.addItem("")
        self.gridLayout.addWidget(self.idexbox, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-image: url(:/R.jpg);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)

        self.typebox = QtWidgets.QComboBox(Form)
        self.typebox.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.typebox.setFont(font)
        self.typebox.setObjectName("idexbox")
        self.typebox.addItem("")
        self.typebox.addItem("")
        self.gridLayout.addWidget(self.typebox, 0, 1, 1, 1)

        self.browser = QWebEngineView()
        self.browser.setMaximumSize(QtCore.QSize(1600,900))
        self.gridLayout.addWidget(self.browser, 1, 0, 4, 4)

        self.pushButton.clicked.connect(self.show_map)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "地图展示"))
        self.idexbox.setItemText(0, _translate("Form", "AQI指数"))
        self.idexbox.setItemText(1, _translate("Form", "PM2.5"))
        self.idexbox.setItemText(2, _translate("Form", "PM10"))
        self.idexbox.setItemText(3, _translate("Form", "So2"))
        self.idexbox.setItemText(4, _translate("Form", "Co"))
        self.idexbox.setItemText(5, _translate("Form", "No2"))
        self.idexbox.setItemText(6, _translate("Form", "O3"))
        self.typebox.setItemText(0, _translate("Form", "相对指标"))
        self.typebox.setItemText(1, _translate("Form", "绝对指标"))
        self.pushButton.setText(_translate("Form", "展示"))

    def show_map(self):
        type = self.typebox.currentText()
        target = self.idexbox.currentText()
        generate_map(target, type)
        url = "E:\pythonProject\暑期实训\文件操作\map\全国.html"
        # print(url)
        self.browser.load(QUrl.fromLocalFile(url))
        self.browser.show()


