# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'picshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_picwid(object):
    def setupUi(self, picwid):
        picwid.setObjectName("picwid")
        picwid.resize(1050, 650)
        font = QtGui.QFont()
        font.setPointSize(16)
        picwid.setFont(font)
        self.pic = QtWidgets.QLabel(picwid)
        self.pic.setGeometry(QtCore.QRect(10, 10, 1010, 610))
        self.pic.setText("")
        self.pic.setObjectName("pic")

        self.retranslateUi(picwid)
        QtCore.QMetaObject.connectSlotsByName(picwid)

    def retranslateUi(self, picwid):
        _translate = QtCore.QCoreApplication.translate
        picwid.setWindowTitle(_translate("picwid", "picture"))


if __name__=="__main__":
    app=QtWidgets.QApplication(sys.argv)
    MainWindow = QWidget()
    ui=Ui_picwid()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
