# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette, QBrush, QPixmap
from PyQt5.QtWidgets import QWidget

from 数据分析.预处理 import city_rank
from 界面 import mainwid


class Ui_rankwid(QWidget):
    def setupUi(self, rankwid):
        rankwid.setObjectName("rankwid")
        rankwid.resize(900, 786)
        rankwid.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        rankwid.setFont(font)

        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap("nuan.jpg")))
        rankwid.setPalette(palette)

        self.gridLayout = QtWidgets.QGridLayout(rankwid)
        self.gridLayout.setObjectName("gridLayout")
        self.showtab = QtWidgets.QTableWidget(rankwid)
        self.showtab.setMaximumSize(QtCore.QSize(850, 500))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.showtab.setFont(font)
        self.showtab.setStyleSheet("border-image: url(:/R.jpg);")
        self.showtab.setObjectName("showtab")
        self.showtab.setColumnCount(6)
        self.showtab.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(16)
        item.setFont(font)
        self.showtab.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.showtab, 2, 1, 1, 6)
        self.citylab = QtWidgets.QLabel(rankwid)
        self.citylab.setMinimumSize(QtCore.QSize(120, 50))
        self.citylab.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.citylab.setFont(font)
        self.citylab.setStyleSheet("border-image: url(:/R.jpg);")
        self.citylab.setObjectName("citylab")
        self.gridLayout.addWidget(self.citylab, 5, 1, 1, 1)
        self.ci1 = QtWidgets.QPlainTextEdit(rankwid)
        self.ci1.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ci1.setFont(font)
        self.ci1.setStyleSheet("border-image: url(:/R.jpg);")
        self.ci1.setObjectName("ci1")
        self.gridLayout.addWidget(self.ci1, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(rankwid)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 6)
        self.orderbox = QtWidgets.QComboBox(rankwid)
        self.orderbox.setMinimumSize(QtCore.QSize(150, 50))
        self.orderbox.setMaximumSize(QtCore.QSize(201, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.orderbox.setFont(font)
        self.orderbox.setStyleSheet("border-image: url(:/R.jpg);")
        self.orderbox.setObjectName("orderbox")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.gridLayout.addWidget(self.orderbox, 0, 1, 1, 1)
        self.okbut = QtWidgets.QPushButton(rankwid)
        self.okbut.setMinimumSize(QtCore.QSize(100, 50))
        self.okbut.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.okbut.setFont(font)
        self.okbut.setStyleSheet("border-image: url(:/R.jpg);\n"
"border-image: url(:/R.jpg);\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    font:20px;\n"
"    color:white;\n"
"    background-color:rgb(14 , 150 , 254);\n"
"    border-radius:15px;\n"
"    height:50px;\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.okbut.setObjectName("okbut")
        self.gridLayout.addWidget(self.okbut, 0, 2, 1, 1)
        self.ci2 = QtWidgets.QPlainTextEdit(rankwid)
        self.ci2.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ci2.setFont(font)
        self.ci2.setStyleSheet("border-image: url(:/R.jpg);")
        self.ci2.setObjectName("ci2")
        self.gridLayout.addWidget(self.ci2, 5, 3, 1, 1)
        self.showbtn = QtWidgets.QPushButton(rankwid)
        self.showbtn.setMinimumSize(QtCore.QSize(100, 50))
        self.showbtn.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.showbtn.setFont(font)
        self.showbtn.setStyleSheet("border-image: url(:/R.jpg);")
        self.showbtn.setObjectName("showbtn")
        self.gridLayout.addWidget(self.showbtn, 5, 4, 1, 1)

        self.okbut.clicked.connect(self.show_rank)

        self.retranslateUi(rankwid)
        QtCore.QMetaObject.connectSlotsByName(rankwid)

    def retranslateUi(self, rankwid):
        _translate = QtCore.QCoreApplication.translate
        rankwid.setWindowTitle(_translate("rankwid", "排名"))
        item = self.showtab.horizontalHeaderItem(0)
        item.setText(_translate("rankwid", "排名"))
        item = self.showtab.horizontalHeaderItem(1)
        item.setText(_translate("rankwid", "城市"))
        item = self.showtab.horizontalHeaderItem(2)
        item.setText(_translate("rankwid", "AQI指数"))
        item = self.showtab.horizontalHeaderItem(3)
        item.setText(_translate("rankwid", "PM2.5"))
        item = self.showtab.horizontalHeaderItem(4)
        item.setText(_translate("rankwid", "空气质量"))
        item = self.showtab.horizontalHeaderItem(5)
        item.setText(_translate("rankwid", "省份"))
        self.citylab.setText(_translate("rankwid", "城市对比"))
        self.orderbox.setItemText(0, _translate("rankwid", "最好排名"))
        self.orderbox.setItemText(1, _translate("rankwid", "最差排名"))
        self.okbut.setText(_translate("rankwid", "OK"))
        self.showbtn.setText(_translate("rankwid", "展示"))

    def show_rank(self):
        for i in range(self.showtab.rowCount()):
            self.showtab.removeRow(0)
        type = self.orderbox.currentText()
        result = city_rank(type)
        for obj in result:
            row = self.showtab.rowCount()
            self.showtab.insertRow(row)
            # print(obj)
            for j in range(0, 6):
                item1 = QtWidgets.QTableWidgetItem(str(obj[j]))
                self.showtab.setItem(row, j, item1)